(()=>{'use strict';
const stages=[
 {id:'p1',code:'P1',name:'Старт курса',short:'Старт курса',time:'В начале курса',description:'Ты начинаешь учиться по обычной программе. Команда расскажет об исследовании и условиях участия.',actions:['Ознакомься с информацией об исследовании и документами своего вуза.','Уточни, где будут появляться даты, инструкции и сообщения команды.'],note:'Точные сроки определяются календарём твоего курса.'},
 {id:'p2',code:'P2',name:'Исходный замер',short:'Исходный замер',time:'До выдачи доступа к AICO',description:'Перед запуском AICO команда фиксирует исходный уровень и учебный контекст участников.',actions:['Пройди входной тест и опросы, если они предусмотрены на твоём курсе.','Следуй инструкции к замеру: правила использования ИИ определяются отдельно.'],note:'Набор тестов, опросов и данных зависит от курса. Этот этап помогает точнее сравнить условия обучения.'},
 {id:'r',code:'R',name:'Назначение доступа',short:'Доступ к AICO',time:'После исходного замера',description:'Команда сообщает, назначен ли тебе доступ к AICO. С этого момента участники учатся в согласованных условиях.',actions:['Если доступ назначен, открой ссылку из сообщения команды и проверь вход.','Если доступа нет, продолжай учиться по обычной программе. Общие замеры остаются частью маршрута.'],note:'Активности внутри AICO не дают официальных баллов и не становятся условием допуска.'},
 {id:'t1',code:'T1',name:'Промежуточный тест',short:'Промежуточный тест',time:'Если предусмотрен на курсе',description:'Небольшой замер помогает понять, как проходит обучение и с какими трудностями сталкиваются участники.',actions:['Выполни тест по инструкции команды курса.','Если предусмотрен опрос, расскажи о нагрузке, использовании ИИ и технических проблемах.'],note:'Формат, срок и правила использования ИИ подтверждаются отдельно. Не на каждом курсе этот этап будет проводиться.'},
 {id:'t2',code:'T2',name:'Итоговый тест',short:'Итоговый тест',time:'В конце основного периода',description:'Главный замер исследования: что ты понимаешь и можешь применить самостоятельно.',actions:['Выполни предметный тест без AICO и других ИИ-сервисов.','Следуй общей инструкции и заполни итоговые опросы, если они предусмотрены.'],note:'Дата и содержание теста привязаны к твоему курсу. Количество сообщений в AICO не заменяет самостоятельный результат.'},
 {id:'t3',code:'T3',name:'Пост-тест',short:'Пост-тест',time:'После итогового теста · если подтверждён',description:'Отсроченный замер помогает понять, что сохранилось в памяти и как знания работают в новой ситуации.',actions:['Уточни у команды, будет ли этот этап на твоём курсе.','Если он проводится, выполни задания самостоятельно, без AICO и других ИИ-сервисов.'],note:'Возможность и дату пост-теста подтверждают отдельно. Он не обязательно повторяет задания итогового теста.'}
];

const examples=[
 'Представь: начинается твой курс. В сообщении команды есть описание исследования и документы вуза. Ты читаешь их и уточняешь, где искать дальнейшие инструкции.',
 'Представь: доступ к AICO ещё не выдан. Команда просит пройти входной тест и опрос. Ты проверяешь инструкцию к замеру и выполняешь предусмотренные задания.',
 'Представь: команда присылает условия участия. Если тебе назначен доступ к AICO, ты проверяешь вход по полученной ссылке. Если нет, продолжаешь обычную программу и участвуешь в согласованных замерах.',
 'Представь: в середине курса команда объявляет промежуточный замер. Если он предусмотрен, ты выполняешь тест по его инструкции и рассказываешь о своём опыте в опросе.',
 'Представь: основной период курса завершён. Ты проходишь предметный тест самостоятельно, без AICO и других ИИ-сервисов, и заполняешь предусмотренные итоговые опросы.',
 'Представь: после итогового теста приходит приглашение на ещё один замер. Если пост-тест подтверждён для твоего курса, ты выполняешь задания самостоятельно, без ИИ.'
];

const $=id=>document.getElementById(id);const modes={brief:{name:'сразу суть'},steps:{name:'по шагам'},example:{name:'на примере'}};let mode=new URLSearchParams(location.search).get('mode');if(!modes[mode])mode='brief';let active=0;const navButtons=[];
function renderStage(animate=false){const s=stages[active];$('event-title').textContent=s.name;$('event-code').textContent=`${s.code} / этап ${active+1} из 6`;$('event-time').textContent=s.time;$('event-note').textContent=s.note;$('next-text').textContent=active===5?'К первому этапу':'Следующий этап';
 const body=$('stage-body');body.replaceChildren();
 if(mode==='example'){const p=document.createElement('p');p.className='event-example';const label=document.createElement('span');label.className='example-label';label.textContent='Возможная ситуация';p.append(label,document.createTextNode(examples[active]));body.append(p);}
 else{const p=document.createElement('p');p.className='event-description';p.textContent=s.description;body.append(p);}
 const heading=document.createElement('h4');heading.textContent=mode==='steps'?'Твои действия по порядку':'Что тебе предстоит';const list=document.createElement(mode==='steps'?'ol':'ul');list.className='event-actions';s.actions.forEach(t=>{const li=document.createElement('li');li.textContent=t;list.append(li);});body.append(heading,list);
}
function selectStage(i,{focus=false,writeHash=true}={}){active=i;navButtons.forEach((b,j)=>b.setAttribute('aria-pressed',String(j===i)));renderStage(false);if(writeHash&&location.hash!==`#stage-${stages[i].id}`)history.pushState(null,'',`#stage-${stages[i].id}`);$('announcer').textContent=`Этап ${i+1} из 6. ${stages[i].name}. ${stages[i].time}.`;if(focus){$('event-title').focus({preventScroll:true});$('event-copy').scrollIntoView({behavior:'instant',block:'start'});}}
stages.forEach((s,i)=>{const li=document.createElement('li'),b=document.createElement('button');b.type='button';b.className='route-button';b.setAttribute('aria-pressed',String(i===0));b.setAttribute('aria-controls','event-copy');b.innerHTML=`<span class="route-num">0${i+1}</span><span class="route-title">${s.name}<span class="route-code">${s.code}</span></span>`;b.addEventListener('click',()=>selectStage(i,{focus:true}));b.addEventListener('keydown',e=>{let j=i;if(e.key==='ArrowRight')j=(i+1)%6;else if(e.key==='ArrowLeft')j=(i+5)%6;else if(e.key==='Home')j=0;else if(e.key==='End')j=5;else return;e.preventDefault();navButtons[j].focus();selectStage(j);});li.append(b);$('route-nav').append(li);navButtons.push(b);});
$('next').addEventListener('click',()=>selectStage((active+1)%6,{focus:true}));
function fromHash(scroll=false){const m=/^#stage-(p1|p2|r|t1|t2|t3)$/.exec(location.hash);if(m){selectStage(stages.findIndex(s=>s.id===m[1]),{writeHash:false});if(scroll)$('route').scrollIntoView({behavior:'instant'});}}
window.addEventListener('hashchange',()=>fromHash(true));window.addEventListener('popstate',()=>fromHash(true));

$('stage-mode').value=mode;$('stage-mode').addEventListener('change',e=>{mode=e.target.value;renderStage();const url=new URL(location.href);url.searchParams.set('mode',mode);history.replaceState(null,'',url);$('announcer').textContent='Объяснение этапа обновлено.';});renderStage();fromHash();})();
